blank_lines_upper_bound = 1
condense_wildcard_suffixes = true
edition = "2021"
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Tall"
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Lower"
inline_attribute_width = 50
max_width = 130
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
